- hosts: all
  become: yes
  remote_user: ubuntu
  ignore_errors: true
  tasks:
   - name: installation of docker
     apt:
      name: curl
      state: present
   - name: download docker script
     shell: curl -fsSL https://get.docker.com -o get-docker.sh && chmod 777 -R get-docker.sh && ./get-docker.sh
   - name: checking version
     shell: docker --version
     register: version
   - name: version
     debug:
      var: version
